version: '3.8'

services:
  backtester:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: crypto_backtester_minimal
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./config.json:/app/config.json
      - ./config_examples.json:/app/config_examples.json
      - ./config_api_examples.json:/app/config_api_examples.json
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py", "--help"]

  backtester-web:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: backtester_web_minimal
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - FLASK_APP=web_app.py
    command: ["python", "web_app.py"]
    depends_on:
      - backtester 